name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: Build proxy
        run: docker build proxy --tag ghcr.io/thedim0n/passlocker/proxy:latest
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Push image
        run: docker push ghcr.io/thedim0n/passlocker/proxy:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
