name: Create JSON

on:
  push:
   paths:
   - 'README.md'
  workflow_dispatch:


jobs:
  create-json:
    uses: TheDim0n/.github/blob/main/.github/workflows/create_json.yml@main
    with:
      username: ${{ secrets.PAT }}
    
